# ref: https://docs.codecov.com/docs/codecovyml-reference
coverage:
  # Hold ourselves to a high bar
  range: 75..100
  round: down
  precision: 6
  status:
    # ref: https://docs.codecov.com/docs/commit-status
    project:
      default:
        # Avoid false negatives
        threshold: 0.5%

# Ignore test files and main.cpp
ignore:
  - "test"
#  - "src/main.cpp"  # <- This line ignores the main C++ file
#  - "src/cli.rs"
#  - "src/utils"

# Make comments less noisy
comment:
  layout: "files"
  require_changes: true