
name: 'setup_cache'
description: 'sets up the shared cache'
inputs:
  compiler:
    required: true
    type: string
  build_type:
    required: true
    type: string
  generator:
    required: true
    type: string
  packaging_maintainer_mode:
    required: true
    type: string


runs:
  using: "composite"
  steps:
    - name: Ensure cache directories exist
      uses: actions/github-script@v8
      with:
        script: |
          const os   = require('os');
          const fs   = require('fs');
          const path = require('path');

          const dirs = [
            path.join(os.homedir(), '.cache', 'pip'),
            path.join(os.homedir(), '.ccache'),
          ];

          for (const dir of dirs) {
            fs.mkdirSync(dir, { recursive: true });
            core.info(`Ensured directory exists: ${dir}`);
          }

    - name: Cache
      uses: actions/cache@v5
      with:
        # You might want to add .ccache to your cache configuration?
        path: |
          ~/.cache/pip
          ~/.ccache
        key: ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}-${{ inputs.generator }}-${{ inputs.packaging_maintainer_mode }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.compiler }}-${{ inputs.build_type }}

